### PR TITLE
Add collapse molecule

### PR DESCRIPTION
**Pull request by dmarcoux**
I don't remember why I closed the previous PR (#40) instead of fixing it. I didn't change anything, I want to see first if it works. There were some weird issues before.

### CODE REVIEW

**Comment by hennevogel** [comment]
Deploy preview for *obs-patterns* ready!

Built with commit 7a6d884415b3d3d5873d3ed18c35cbd5b9893f22

https://deploy-preview-54--obs-patterns.netlify.com

**Comment by dmarcoux** [comment]
As expected, still not working completely. I'll look into it...

**Comment by dmarcoux** [comment]
I found the issue. It was the duplication of the external libraries (jQuery, etc...)

**Comment by dmarcoux** [comment]
@openSUSE/obs-frontend Please have a look

**Review by eduardoj — APPROVED** [review]

**Pull request merged**
