### PR TITLE
Add table component

### PR DESCRIPTION
**Pull request by dmarcoux**
Part of https://github.com/openSUSE/open-build-service/pull/5713

### CODE REVIEW

**Comment by hennevogel** [comment]
Deploy preview for *obs-patterns* ready!

Built with commit a31b11c44608e2cbc873a4609b280b7c77e99a8c

https://deploy-preview-15--obs-patterns.netlify.com

**Review by bgeuken — CHANGES_REQUESTED** [review]
Looks good, but please update the column entries. Right now they are quite inconsistent, going from 'something' to 'Lorem Ipsum' to 'test 567' :smile:

**Comment by dmarcoux** [comment]
@bgeuken I wasn't really inspired. I went this time with some openSUSE-themed column entries. Better? :smile:

**Comment by bgeuken** [comment]
Definitely:+1:

**Review by bgeuken — APPROVED** [review]

**Pull request merged**
