### PR TITLE
Add switch to the forms molecule

### PR DESCRIPTION
**Pull request by dmarcoux**
We started to use it in the search pages.

### CODE REVIEW

**Comment by hennevogel** [comment]
Deploy preview for *obs-patterns* ready!

Built with commit 46b9339112efb8d59e28d791954caee0896ad086

https://deploy-preview-62--obs-patterns.netlify.com

**Review by bgeuken — APPROVED** [review]

**Review by bgeuken — CHANGES_REQUESTED** [review]
Just realizing it'S not having the primary color

**Comment by dmarcoux** [comment]
What do you mean by the primary color? When it's checked (or switched on in this case), it's green, just like the primary color.

**Comment by bgeuken** [comment]
Ah, I didn't try that:+1:

**Review by bgeuken — APPROVED** [review]

**Pull request merged**
