### PR TITLE
Document how styled tables / DataTables look like in OBS

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by hennevogel** [comment]
Deploy preview for *obs-patterns* ready!

Built with commit 9580a381af0ef4c9e95296aaa51b28f4171d457a

https://deploy-preview-16--obs-patterns.netlify.com

**Comment by bgeuken** [comment]
I was wondering how we could distinguish between the different table styles we have in OBS. Should we change the labels to something like `Table (plain)` and `DataTable (styled)` or `Table (styled with DataTable)`?

**Review by dmarcoux — COMMENTED** [review]
I believe that we should style the DataTable and the Table component the same way.

**Comment by DavidKang** [comment]
@dmarcoux, I agree with you.

**Comment by eduardoj** [comment]
@bgeuken:

> I was wondering how we could distinguish between the different table styles we have in OBS. Should we change the labels to something like `Table (plain)` and `DataTable (styled)` or `Table (styled with DataTable)`?

If we already have cases where different table styles apply: yes, reasoning each of them. We can always start easy, only with one style, and add more styles later in case they are needed.

DataTable and Table are fine for me now.

**Review by eduardoj — APPROVED** [review]

**Comment by bgeuken** [comment]
> dmarcoux reviewed 6 hours ago
> I believe that we should style the DataTable and the Table component the same way.

That sounds reasonable. Though, right now we have a few cases were we use a different style (visually and functionality wise) for tables, eg. the project monitor table. And in some cases we might want a table but not the whole DataTable functionality.

**Pull request merged**
