### PR TITLE
Design decisions

### PR DESCRIPTION
**Pull request by dmarcoux**
- [X] Colors
- [X] Icons
- [X] Buttons
- [X] Typography

Co-authored-by: Victor Pereira <vpereira@suse.com>

### CODE REVIEW

**Comment by hennevogel** [comment]
Deploy preview for *obs-patterns* ready!

Built with commit bc4be98e9ee205896a47af34805fd5b5c86415e3

https://deploy-preview-21--obs-patterns.netlify.com

**Comment by dmarcoux** [comment]
[Decide on basic design decisions](https://trello.com/c/kCNmcNpM/863-decide-on-basic-design-decisions)

**Comment by bgeuken** [comment]
One observation... There is a wide variation of colors for the icons. I tend to think that we should align them a bit. Like using the one color code for blue and also only one color type for the dark-grey icons.

That said I am not a design expert :wink:

**Comment by dmarcoux** [comment]
@bgeuken I agree with you. I added some questions for reviewers in this PR's description. I believe we should only have one tone for each color. Let's see if the team agrees.

**Comment by vpereira** [comment]
one tone, don't make me think!

**Comment by hennevogel** [comment]
>  Let's see if the team agrees.

We do not need to design by committee. You two discovered an obvious 'bug'. Fix it :-)

A good way to think of this for Engineers is: Would I discuss a similar change in code with the team? If yes, discuss the design thing in the team too. If not then **don't**.

**Comment by bgeuken** [comment]
Well, that's why we have a PR. So that the OBS team can review and discuss it:-) And I think that's what Dany meant

**Review by bgeuken — APPROVED** [review]
LGTM,

regarding the TODOs... are they still valid? If they are I would prefer to convert them to issues. That said I can life with leaving them where they are.

**Review by hennevogel — CHANGES_REQUESTED** [review]
I think colors and icons are not components. In the bootstrap docu this stuff is called **Content**

**Comment by dmarcoux** [comment]
I would like to go over the typography. For the autocomplete, I agree with having an issue for it or a card in Trello.

**Comment by vpereira** [comment]
> I think colors and icons are not components. In the bootstrap docu this stuff is called **Content**

the collection of user interface parts for an application, such as forms,  navigational elements, buttons, and alerts is normally called "Pattern Library", a sub-group for buttons, alerts and so on, "Widgets" (but maybe it's too 90s) . Components are normally external libraries or frameworks used to build the application. Said that, I see the icons as components in the bootstrap website @hennevogel  https://getbootstrap.com/docs/3.3/components/ 


BTW: this project maintained by RH is a good reference https://www.patternfly.org/

**Comment by hennevogel** [comment]
> I see the icons as components in the bootstrap website

Maybe you want to look at the version we are using :-)

**Comment by hennevogel** [comment]
And the words don't really matter. It's the distinction that does.

**Review by hennevogel — APPROVED** [review]

**Comment by dmarcoux** [comment]
@openSUSE/obs-frontend Please review this and let us know if we need to change something. Once this is merged, we will need to adapt our Bootstrap views to follow this.

**Comment by bgeuken** [comment]
I only have one nitpick / feature request: It would be awesome if the [refresh icon](https://deploy-preview-21--obs-patterns.netlify.com/content/icons.html) would rotate on click.

Other than that, great work :thumbsup:

**Comment by hennevogel** [comment]
I don't really see the point in repeating all the bootstrap typography documentation. And I wish we would not stick to all defaults :-)

**Comment by dmarcoux** [comment]
@hennevogel I decided to repeat some parts of the Bootstrap documentation, but only the ones I believe we should use. This way, we don't have to go through the documentation for searching how to do something related to typography.

For the defaults, I am not so sure about which font family we should use. I'm open to suggestions!

**Comment by dmarcoux** [comment]
@bgeuken Done for the rotate on click.

**Review by DavidKang — APPROVED** [review]

**Comment by hennevogel** [comment]
> This way, we don't have to go through the documentation for searching how to do something related to typography.

That's why I said we need to talk about the scope of this thing this morning... I will set up a meeting for next week.

**Comment by bgeuken** [comment]
> @bgeuken Done for the rotate on click.
--

Awesome! Thank you :tada:

**Comment by ChrisBr** [comment]
LGTM

**Pull request merged**
