### PR TITLE
Document that we use custom forms

### PR DESCRIPTION
**Pull request by bgeuken**
http://getbootstrap.com/docs/4.1/components/forms/#custom-forms

### CODE REVIEW

**Comment by hennevogel** [comment]
Deploy preview for *obs-patterns* ready!

Built with commit 6f0ef8e3edda29bcbe77440f46b893a435e25873

https://deploy-preview-22--obs-patterns.netlify.com

**Comment by dmarcoux** [comment]
@bgeuken Fixed the link in the description to point to the version of Bootstrap we use (so `4.1` instead of `4.0`.

**Comment by ChrisBr** [comment]
Is this only true for radio and checkbox? What about the select and file browse? Otherwise LGTM

**Comment by dmarcoux** [comment]
@ChrisBr I added the select and file browse. Please review

**Review by dmarcoux — APPROVED** [review]

**Pull request merged**
