### PR TITLE
Add dropdown with checkbox atom

### PR DESCRIPTION
**Pull request by ChrisBr**

### CODE REVIEW

**Comment by hennevogel** [comment]
Deploy preview for *obs-patterns* ready!

Built with commit 51625e6d5afe14ebf7d6ea3419ef99c9ac272da6

https://deploy-preview-47--obs-patterns.netlify.com

**Comment by hennevogel** [comment]
Are you sure we are going to reuse this pattern?

**Comment by dmarcoux** [comment]
It should be in the _Molecules_ group

**Comment by ChrisBr** [comment]
> Are you sure we are going to reuse this pattern?

Hm, I think so? At least it took some time to build it so I would like to document it somewhere, no?

**Comment by hennevogel** [comment]
> Hm, I think so?

Fair enough :-)

**Review by bgeuken — CHANGES_REQUESTED** [review]
This looks broken

screenshot from 2018-12-14 14-44-49

**Comment by ChrisBr** [comment]
Yeah, I know, sorry :cry: Won't have time to fix it today. We can close until next year or just leave it dangling as reminder ...

**Review by bgeuken — APPROVED** [review]

**Comment by bgeuken** [comment]
Alright. I solved the 'span' issue by moving the dropdown into a div and I also moved the whole pattern from the atom section to the molecules.

**Pull request merged**
